# Descargamos la imagen
FROM node:slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia el package.json y el package-lock.json
COPY package.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos al contenedor
COPY . .

# Expone el puerto de la aplicación
EXPOSE 3000

# Comando de inicio
CMD ["node", "src/index.js"]